# Generated by Django 6.0.2 on 2026-02-24 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_plan', '0002_conversationsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='best_seasons',
            field=models.CharField(blank=True, help_text='مثال: صيف,ربيع أو شتاء,خريف', max_length=100),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('season', models.CharField(choices=[('summer', 'صيف'), ('winter', 'شتاء'), ('spring', 'ربيع'), ('autumn', 'خريف'), ('all', 'كل المواسم')], max_length=50)),
                ('price_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_hours', models.PositiveIntegerField(default=2)),
                ('is_free', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='trip_plan.destination')),
            ],
        ),
    ]
