# Generated by Django 6.0.2 on 2026-02-24 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_plan', '0003_event_and_best_seasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageasset',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='trip_plan.event'),
        ),
    ]
